### PR TITLE
add batch file for easy install/remove

### PR DESCRIPTION
**Pull request by KptnKMan**
I created this INSTALL/REMOVE script for easy installation/removal of the OculusKiller mod.
I have tested this script extensively, and it works without issues in all my testing on Windows 10 with latest updates.

The use of this script is pretty easy, create a folder anywhere, and place the modified OculusDash.exe and this script in that folder.
This folder can be anywhere on your PC, I created a folder in My Documents, and run it from there. You could put it anywhere, as long as the modified OculusDash.exe is there as well.

Always run the script AS ADMINISTRATOR, or you will get an "Access Denied" error.
I would recommend including this script with further releases, as a combined zip file which will make install and removal easy.

### CODE REVIEW

**Comment by dinckelman** [comment]
There's a really big issue with this workaround. It assumes that your oculus server is installed in the default location. Without giving path manually, or setting Oculus path into $PATH, as far as I can't tell, you can't determine that at runtime

**Comment by UnusualNorm** [comment]
@dinckelman Good point, on that note. We do in fact have a way to check that, we have the OCULUSBASE environment variable.

@KptnKMan Instead of pre-defining the Oculus installation location, please make use of the OCULUSBASE environment variable to determine where to place files.

**Comment by dinckelman** [comment]
Patch submitted, waiting on @KptnKMan to approve the PR [here](https://github.com/KptnKMan/OculusKiller/pull/1)

**Comment by KptnKMan** [comment]
Copy and Paste of the same comment from the patch:

So I think the point of this script purposefully NOT being Powershell is missed here.
Powershell is great and all and I could have done that, but because of Powershells own greatness, there are often issues with Powershell scripts (PSVersion, Execution Permissions, Libraries, etc).
The point is this script was written PURPOSEFULLY in batch because it runs with better compatibility and different versions of Windows.

I have updated the script after I saw the first comment, but I didn't see the rest until now.
I have also added additional functionality to detect if the OCULUSBASE variable exists, and create it (per users permission by asking the user). Also, a custom path can be entered, and that can be written as a System Var as well if desired.

Again, the point is that batch is more compatible with more systems, and I think it will work for more people, and easier, without then needing to configure Powershell first.

So, the patch is rejected.
But you can submit your own PR, matters not to me.

On a final note, it would have taken like 2 lines extra just to add %OCULUSBASE% but hey, lets use our Powershell skills I guess.

**Comment by KptnKMan** [comment]
I've also made sure to test this script on different Windows OSs because not everyone uses latest Windows 10.
Windows 10 and Windows 7 should work, again, without the Powershell shenanigans.

The purpose is compatibility.

**Comment by whatdahopper** [comment]
Outside of the scope of this project, I do not think it requires a neurosurgeon to install OculusKiller, it is a simple file replacement. As long as you know how to rename files and move them, it's not hard.

**Comment by KptnKMan** [comment]
Well I'm so glad we came to THAT conclusion after TWO AND A HALF YEARS. ❤️

**Comment by whatdahopper** [comment]
> Well I'm so glad we came to THAT conclusion after TWO AND A HALF YEARS. ❤️

I am so sorry it took this long, I'll wait 4 years the next time for the next update.

**Pull request closed without merging**
