### PR TITLE
Exit (Air)Link when SteamVR exits!

### PR DESCRIPTION
**Pull request by UnusualNorm**
It's the long awaited thing! SteamVR no longer automagically restarts when you want to exit (Air)Link!
I have no idea how this affects Rift users as mine is currently in storage, please test if you do though.

This PR simply kills the OVRServer_x64.exe when vrserver.exe exits, thus, killing (Air)Link. But there's more room for error.
@HyrumGG If you could please review this and correct my stupidity, I did not find a way to run .Find on the array, so I resorted to using loops. Please submit a PR if you do find a way to do that, thanks!

### CODE REVIEW

**Comment by UnusualNorm** [comment]
Just an update about my inability to find the Array.Find, I found out how to do it with the latest commit. Although it goes untested as I am not currently home, I will edit this message when I build and test the latest commit.

**Comment by UnusualNorm** [comment]
Woops, I hit the wrong button :(

**Comment by HyrumGG** [comment]
I will look at this after work today

**Comment by UnusualNorm** [comment]
@HyrumGG Thanks! Unfortunately, the latest commit is broken, as I have programmed it in VSCode... I am releasing a better and fixed commit later today though. Sorry for the inconvenience.

**Comment by UnusualNorm** [comment]
Cool! Fixed everything @HyrumGG! Please check to see if there is any optimizations/fixes I could make, thanks in advance!

**Review by HyrumGG — APPROVED** [review]
Made the appropriate changes

**Comment by GlaZedBelmont** [comment]
Any idea when this would be merged? it's a very important change imo since it would solve the fact that the oculus button doesn't work

**Comment by UnusualNorm** [comment]
@GlaZedBelmont Unfortunately, this PR would not solve the issue of the Oculus button being unusable. This solves the issue where the "Exit VR" button would simply restart SteamVR instead of closing Oculus Link.

**Comment by GlaZedBelmont** [comment]
I mean, there's no other use to the oculus button other than quitting link in that context

**Comment by GlaZedBelmont** [comment]
So yes it does "fix" it by giving us a way to leave link that's not "kill steamVR and open the oculus menu while steamVR is still dead"

**Comment by lukecarbis** [comment]
Any update on this?

**Comment by ThatOneGal** [comment]
Anything?

**Comment by GlaZedBelmont** [comment]
@ItsKaitlyn03 @HyrumGG could you review and possibly merge this PR? it's been inactive for a while

**Comment by JulianCaruso** [comment]
Hi @ItsKaitlyn03 @HyrumGG ! Also pushing this :)

**Comment by Eliminater74** [comment]
Can this be reviewed and merged>> this PR has been inactive for a while and seems nothing is doing anything more with it.
but this PR would make life so much easier for peepz that rely on AirLink..

**Comment by kayteck1** [comment]
Any progress in this matter?
I very often switch between native Quest2 and SteamVR and the only way to go back to Quest2 from SteamVR I found is to restart the headset.
SteamVR still restarts after selecting Exit SteamVR.

**Comment by MaxMls** [comment]
> Any progress in this matter? I very often switch between native Quest2 and SteamVR and the only way to go back to Quest2 from SteamVR I found is to restart the headset. SteamVR still restarts after selecting Exit SteamVR.

You can download the version with these changes using the following link:
https://github.com/UnusualNorm/OculusKiller/releases/tag/Anti-Restart-Forgiveness

**Comment by Identifier** [comment]
Hey @Eliminater74 and @MaxMls, I happened to also start working on this problem today (before I knew about your work), and I noticed you're waiting up to 10 seconds for vrserver to start because apparently you often ran into the case where vrserver couldn't be found.  Well, it might be because *sometimes*, vrstartup.exe doesn't exit.  Usually it does, but sometimes it doesn't.  I've noticed that usually, the steps happen in this order:

OVRServer_x64.exe starts our killer OculusDash.exe
OculusDash.exe starts vrstartup.exe
vrstartup.exe starts vrmonitor.exe
vrmonitor.exe starts vrserver.exe
--- usually, at this point, vrstartup.exe exits.  This is where the original OculusKiller exits, causing the infinite startup problem.

But sometimes, vrstartup.exe doesn't exit until vrserver and vrmonitor exit.  In this case, you'r stuck on line 24 (`Process.Start(startupPath).WaitForExit();`) until vrserver and vrmonitor have already exited, which may be why you couldn't find it with `Process.GetProcessesByName("vrserver")`

**Comment by Identifier** [comment]
I actually have a kind of serious issue that I'm currently troubleshooting.  On my machine, if the headset disconnects (e.g. because OculusClient is closed, or OVRService is stopped) while SteamVR is still running, my CPU and GPU will go to 100% and hang the machine for a few minutes.  I don't know if it's because I'm also running Desktop+ or what, but it's a total pain.  So I'm trying to add some code that will check for when vrservice is running but OVRService is not, and kill vrservice.

**Comment by Identifier** [comment]
FYI I've created another PR (https://github.com/LibreQuest/OculusKiller/pull/84) that automatically closes SteamVR if the user exited by closing the Oculus app (or stopped the service).  It doesn't do nearly as much error checking as yours, but I just wanted to put it up there just in case it was useful to you guys.

**Comment by Eliminater74** [comment]
I revised the code and made many changes for performance and timing, I didnt create a pull request because I made way tomany
changes and just didnt think it was worth wile to do, but here is the link of what I did,

https://github.com/DevOculus-Meta-Quest/OculusKiller if anyone is interested. I took the Ideas that everyone had and tried my best to time it all right. so far it works great.. maybe a little to good. but let others see it and see if they can fix it up more.. Most of the code from the Original has been refactored..

**Comment by whatdahopper** [comment]
Closing as I have merged @Identifier's PR.

**Pull request closed without merging**
